disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - nesting
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
  - unowned_in_kcapture

included:
  - bubu

excluded:
  - bubu/Data/Bubu.xcdatamodeld

line_length: 160
type_body_length: 400
file_length: 500

identifier_name:
  min_length: 2

reporter: "xcode"